name: publish
permissions: write-all

on:
  push:
    branches:
      - main
      - dev
      - dockerPB

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the ChatSQL Docker image
        run: |
          cd ChatSQL
          docker build . --tag ghcr.io/torchlight-swe2324/chatsql-docker:latest
          docker push ghcr.io/torchlight-swe2324/chatsql-docker:latest
