name: publish

on:
  push:
    branches-ignore:
      - '*'

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the CatSQL Docker image
        run: |
          docker build . --tag ghcr.io/Torchlight-SWE2324/chatsql-docker:latest
          docker push ghcr.io/Torchlight-SWE2324/chatsql-docker:latest
